name = "terminal"
license = "MIT"
licenselink = "https://github.com/zquestz/hugo-theme-terminal/blob/master/LICENSE.md"
description = "A simple, retro theme for Hugo."
homepage = "https://github.com/zquestz/hugo-theme-terminal/"
tags = ["blog", "clean", "customizable", "dark", "highlighting", "minimal", "monotone", "multilingual", "personal", "responsive", "simple", "technical", "retro"]
features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.74

[author]
  name = "zquestz"
  homepage = "https://greyh.at"
  github = "https://github.com/zquestz"
